image: docker:20.10.24

variables:
  POSTGRES_DB: "test_db"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "postgres"
  POSTGRES_HOST: "db"
  PYTHON_VERSION: "3.9"

services:
  - docker:20.10.24-dind

stages:
  - build
  - test

before_script:
  - docker info
  - docker compose version

build:
  stage: build
  script:
    - test -f docker/entrypoint.sh || echo "#!/bin/sh" > docker/entrypoint.sh
    - chmod +x docker/entrypoint.sh
    - docker compose build

test:
  stage: test
  script:
    - docker compose up -d
    - timeout 60s sh -c 'until docker compose exec db pg_isready -h db -p 5432; do sleep 2 ; done'

    # Install dependencies
    - docker compose exec web pip install -U pip
    - docker compose exec web pip install -r requirements.txt
    - docker compose exec web pip install coverage

    # Run coverage and fail if coverage is too low
    - docker compose exec web coverage run manage.py test --noinput
    - docker compose exec web coverage report --fail-under=80
    - docker compose exec web coverage html
    - docker compose exec web coverage xml

    # Optional: Kopiere Reports für manuelles Downloaden aus dem Web-Container (nicht zwingend)
    - docker cp $(docker compose ps -q web):/app/htmlcov ./htmlcov
    - docker cp $(docker compose ps -q web):/app/coverage.xml ./coverage.xml

  artifacts:
    paths:
      - htmlcov/
      - coverage.xml
    expire_in: 1 week

after_script:
  - docker compose down
