version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DEBUG: "0"
      TRANSFORMERS_CACHE: "/cache/transformers"
      SENTENCE_TRANSFORMERS_HOME: "/cache/transformers"
    volumes:
      - /cache:/cache

  db:
    profiles: ["ci"]

  elasticsearch:
    profiles: ["ci"]

  vektor:
    profiles: ["!ci"]

volumes:
  postgres_data:
  es_data:
  model_cache:
