version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.ci  # Use custom Dockerfile name explicitly
    volumes:
      - .:/app
      - /cache/pip:/root/.cache/pip   # Mount pip cache
    environment:
      - ELASTICSEARCH_DSL_HOSTS=${ELASTICSEARCH_DSL_HOSTS}
    depends_on:
      - db
      - elasticsearch

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1

volumes:
  pgdata:
