version: '3.8'

services:
  web:
    profiles: ["ci"]
    build:
      cache_from:
        - ${CI_REGISTRY_IMAGE}/web:${CI_COMMIT_REF_SLUG}
      cache_to: type=local,dest=/cache/docker,mode=max
    environment:
      DEBUG: "0"
      TRANSFORMERS_CACHE: "/cache/transformers"
      SENTENCE_TRANSFORMERS_HOME: "/cache/transformers"
    volumes:
      - /cache:/cache

  db:
    profiles: ["ci"]

  elasticsearch:
    profiles: ["ci"]

  vektor:
    profiles: ["!ci"]

volumes:
  postgres_data:
  es_data:
  model_cache: