# docker-compose.override.yml
version: '3.8'

services:
  db:
    volumes: []  # Don't persist DB in CI
  elasticsearch:
    volumes: []  # Don't persist ES in CI
  vektor:
    volumes: []  # Don't persist Qdrant in CI
