[mypy]
plugins = mypy_django_plugin.main

[mypy.plugins.django-stubs]
django_settings_module = django_backend.settings

[mypy-django_backend.*]
ignore_missing_imports = True

[mypy-movies.*]
[mypy-review.*]
[mypy-tags.*]
[mypy-user.*]
[mypy-tmdb.*]
ignore_missing_imports = True
