# Dockerfile.ci
FROM python:3.10-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PIP_NO_CACHE_DIR=off \
    TRANSFORMERS_CACHE=/cache/transformers \
    TORCH_HOME=/cache/torch \
    SENTENCE_TRANSFORMERS_HOME=/cache/sentence_transformers

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc \
    libpq-dev \
    curl \
    docker.io \
    && rm -rf /var/lib/apt/lists/* \
    && mkdir -p /usr/local/lib/docker/cli-plugins \
    && curl -SL https://github.com/docker/compose/releases/download/v2.27.1/docker-compose-linux-x86_64 \
         -o /usr/local/lib/docker/cli-plugins/docker-compose \
    && chmod +x /usr/local/lib/docker/cli-plugins/docker-compose

COPY requirements-test.txt ./

RUN pip install --upgrade pip && \
    pip install --no-cache-dir --no-deps -r requirements-test.txt


COPY . .

RUN mkdir -p /cache/transformers /cache/torch /cache/sentence_transformers
