# Generated by Django 4.2.7 on 2025-09-02 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_streamingprovider_movieproviderlink_and_more'),
        ('review', '0002_moviequizreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviequizreview',
            name='user_level_at_review',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='moviequizreview',
            name='vector_effect',
            field=models.JSONField(default=dict),
        ),
        migrations.CreateModel(
            name='VectorHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vibe_vector', models.JSONField(blank=True, null=True)),
                ('narrative_vector', models.JSONField(blank=True, null=True)),
                ('style_vector', models.JSONField(blank=True, null=True)),
                ('change_source', models.CharField(choices=[('review', 'Review'), ('manual', 'Manual Adjustment'), ('system', 'System Update')], max_length=50)),
                ('source_id', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vector_history', to='movies.movie')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['movie'], name='review_vect_movie_i_88a7e5_idx'), models.Index(fields=['created_at'], name='review_vect_created_36887c_idx')],
            },
        ),
    ]
