# Generated by Django 4.2.7 on 2025-07-30 10:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('original_title', models.CharField(max_length=50)),
                ('synopsis', models.TextField()),
                ('plot', models.TextField(null=True)),
                ('tagline', models.CharField(max_length=255)),
                ('language', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=4)),
                ('release_date', models.DateField()),
                ('runtime', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)])),
                ('director', models.CharField(max_length=100)),
                ('cast', models.JSONField(default=list)),
                ('genres', models.JSONField(default=list)),
                ('keywords', models.JSONField(default=list)),
                ('composer', models.JSONField(default=list)),
                ('poster_url', models.URLField(max_length=500)),
                ('backdrop_url', models.URLField(max_length=500)),
                ('trailer_url', models.URLField(blank=True, max_length=500, null=True)),
                ('avg_rating', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('tmdb_id', models.IntegerField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Movie',
                'ordering': ['-release_date'],
            },
        ),
    ]
