# Generated by Django 4.2.7 on 2025-08-19 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='plot_normalized',
            field=models.TextField(null=True),
        ),
    ]
