# Generated by Django 4.2.7 on 2025-08-26 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_plot_normalized'),
    ]

    operations = [
        migrations.CreateModel(
            name='StreamingProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('logo_path', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'StreamingProvider',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MovieProviderLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_type', models.CharField(choices=[('flatrate', 'Flatrate'), ('buy', 'Buy'), ('rent', 'Rent')], max_length=20)),
                ('link', models.URLField(blank=True, null=True)),
                ('country', models.CharField(default='DE', max_length=5)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.streamingprovider')),
            ],
            options={
                'db_table': 'MovieProviderLink',
                'unique_together': {('movie', 'provider', 'access_type', 'country')},
            },
        ),
        migrations.AddField(
            model_name='movie',
            name='streaming_providers',
            field=models.ManyToManyField(blank=True, related_name='movies', through='movies.MovieProviderLink', to='movies.streamingprovider'),
        ),
    ]
